# test
name: version, tag and github release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
      - name: Check if version already exists
        id: version-check
        run: |
          if [[ "\"$(npx -y git-conventional-commits version)\"" == "$(npm pkg get version)" ]];
          then
            echo "skipped=true" >> $GITHUB_OUTPUT
          else
            echo "skipped=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup git
        if: ${{ steps.version-check.outputs.skipped == 'false' }}
        run: |
          git config --global user.email $(npm pkg get author.email)
          git config --global user.name $(npm pkg get author.name)
      - name: Generate oclif README
        if: ${{ steps.version-check.outputs.skipped == 'false' }}
        id: oclif-readme
        run: |
          pnpm install
          pnpm run build
          pnpm exec oclif readme
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -am "chore: update README.md"
            git push -u origin ${{ github.ref_name }}
          fi
      - name: Conventional Changelog Action
        if: ${{ steps.version-check.outputs.skipped == 'false' }}
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
      - name: Update draft release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        if: ${{ steps.version-check.outputs.skipped == 'false' }}
        with:
          name: ${{ steps.changelog.outputs.tag }}
          tag: v${{ steps.changelog.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
          body: ${{ steps.changelog.outputs.clean_changelog }}
